name: Labels

on:
  issues:
    types: [opened]

jobs:
  change-label:
    runs-on: ubuntu-latest

    env:
      FOUNDATION_MEMBERS: '["lnkuiper"]'

    steps:
      - name: Label Issue Foundation Member
        if: ${{ contains(fromJson(env.FOUNDATION_MEMBERS), github.event.issue.user.login) }}
        uses: andymckay/labeler@master
        with:
          add-labels: "bug"
