name: Labels

on:
  issues:
    types: [opened]

jobs:
  change-label:
    runs-on: ubuntu-latest
    steps:
      - name: Label Issue Foundation Member
        if: ${{ equals(github.event.issue.user.login, 'lnkuiper') }}
        uses: andymckay/labeler@master
        with:
          add-labels: "bug"
